language: node_js
node_js:
 - "10"
 - "12"
 - "node"
install: npm install --ignore-scripts
script:
  - npm run build
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
